DROP TABLE IF EXISTS LIBRARY;
 
create table LIBRARY (
        id integer generated by default as identity,
        name varchar(255) NOT NULL,
        primary key (id)
    );

DROP TABLE IF EXISTS BOOK;
    create table BOOK (
        id integer generated by default as identity,
        book_name varchar(255) NOT NULL,
        isbn_no varchar(255) NOT NULL,
        lib_id integer NOT NULL,                  
        primary key (id)
    );
	
	
	
	alter table BOOK                        
        add constraint FK355D0780BC290DFE 
        foreign key (lib_id) 
        references LIBRARY;